[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt && python manage.py migrate --noinput && python manage.py collectstatic --noinput"

[deploy]
startCommand = "gunicorn homebite.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/api/"
healthcheckTimeout = 100


